services:
  lecture-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omstu-lecture
    ports: 
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql://omstu:${POSTGRES_PASSWORD}@omstu-postgres/omstu_db
      - GIGACHAT_API=${GIGACHAT_API}
      - GIGACHAT_SCOPE=${GIGACHAT_SCOPE}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
    networks:
      - omstu-network
    restart: unless-stopped

networks:
  omstu-network:
    external: true